n = input('Digite algo: ')
print('O tipo primitivo desse algo é:',type(n))
print('Só tem espaços?', n.isspace())
print('È um número? ', n.isnumeric())
print('È alfabético? ', n.isalpha())
print('È alfanumérico? ', n.isalnum())
print('Está em maiúsculo? ', n.isupper())
print('Está em minúsculo? ', n.islower())
print('Está captalizada? {}'.format(n.istitle()))
